apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regenbogen-ice.fullname" . }}
  labels:
    {{- include "regenbogen-ice.labels" . | nindent 4 }}
stringData:
  token: {{ required "A valid discord token is required." .Values.bot.token }}
  {{- if .Values.bot.sentry.enabled }}
  sentry_dsn: {{ required "A valid sentry dsn is required when using sentry" .Values.bot.sentry.dsn }}
  {{- end }}
