apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "regenbogen-ice.fullname" . }}
  labels:
    {{- include "regenbogen-ice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "regenbogen-ice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "regenbogen-ice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: {{ include "regenbogen-ice.tokenSecretKey" . }}
                  name: {{ include "regenbogen-ice.tokenSecretName" . }}
            - name: SENTRY_DSN
              {{- if .Values.bot.sentry.enabled }}
              valueFrom:
                secretKeyRef:
                  key: {{ include "regenbogen-ice.sentrySecretKey" . }}
                  name: {{ include "regenbogen-ice.sentrySecretName" . }}
              {{- else }}
              value: ""
              {{- end}}
            - name: MONGO_HOST
              value: {{ include "mongodb.fullname" .Subcharts.mongodb }}
            - name: MONGO_URL
              value: "mongodb://$(MONGO_HOST)"
            - name: MONGO_DATABASE
              value: {{ .Values.bot.database }}
          ports:
            - name: liveness-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: liveness-port
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
