{{- if (include "regenbogen-ice.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regenbogen-ice.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "regenbogen-ice.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.bot.token }}
  token: {{ .Values.bot.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.bot.sentry.dsn }}
  sentry_dsn: {{ .Values.bot.sentry.dsn | b64enc | quote }}
  {{- end }}
{{- end -}}
