{{- if (or (and .Values.bot.existingSecret .Values.bot.existingSecretKey (not .Values.bot.token) (and .Values.bot.sentry.existingSecret .Values.bot.sentry.existingSecretKey (not .Values.bot.sentry.dsn)))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regenbogen-ice.fullname" . }}
  labels:
    {{- include "regenbogen-ice.labels" . | nindent 4 }}
stringData:
  {{- if .Values.bot.token }}
  token: {{ required "A valid discord token is required." .Values.bot.token }}
  {{- end }}
  {{- if .Values.bot.sentry.dsn }}
  sentry_dsn: {{ required "A valid sentry dsn is required when using sentry" .Values.bot.sentry.dsn }}
  {{- end }}
{{- end}}
